// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Subsystems/MainDrive.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

MainDrive::MainDrive() : frc::Subsystem("MainDrive") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
speedController1.reset(new frc::PWMVictorSPX(4));
AddChild("Speed Controller 1", std::static_pointer_cast<frc::PWMVictorSPX>(speedController1));

speedController2.reset(new frc::PWMVictorSPX(1));
AddChild("Speed Controller 2", std::static_pointer_cast<frc::PWMVictorSPX>(speedController2));

speedController3.reset(new frc::PWMVictorSPX(2));
AddChild("Speed Controller 3", std::static_pointer_cast<frc::PWMVictorSPX>(speedController3));

speedController4.reset(new frc::PWMVictorSPX(3));
AddChild("Speed Controller 4", std::static_pointer_cast<frc::PWMVictorSPX>(speedController4));

mecanumDrive1.reset(new frc::MecanumDrive(*speedController1, *speedController2,
              *speedController3, *speedController4));
AddChild("Mecanum Drive 1", mecanumDrive1);
mecanumDrive1->SetSafetyEnabled(true);
mecanumDrive1->SetExpiration(0.1);
mecanumDrive1->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void MainDrive::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void MainDrive::Periodic() {
    // Put code here to be run every loop

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.

